### ISSUE TITLE
Cannot run using py -3.9

### ISSUE THREAD

**Issue by Ernestas-S** [mbrav/ansible-inventory-diagram#1]
PS ansible-inventory-diagram> py -3.9 .\diagram\main.py
Traceback (most recent call last):
  File "ansible-inventory-diagram\diagram\main.py", line 4, in <module>
    from graph import InventoryGraph
  File "ansible-inventory-diagram\diagram\graph.py", line 8, in <module>
    class AnsibleHost:
  File "ansible-inventory-diagram\diagram\graph.py", line 13, in AnsibleHost
    node: Node | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by mbrav** [comment]
Hi, @Ernestas-S ! The `|` operand was added in python 3.10, so not available in python 3.9.

Version 3.10 or higher is required to run ansible-inventory-diagram. In case you need to install Python of any version I can recommend setting up [pyenv](https://github.com/pyenv/pyenv) and then installing the latest Python 3.10 version:

```shell
pyenv install 3.10.13
pyenv activate 3.10.13
```

**Comment by Ernestas-S** [comment]
I see, thank you for adding prerequisites for python requirements.

Also to be be able to run it with Python 3.9, one can add
`__future__ import annotations`
 to the graph.py file.
